# Generated by Django 5.1.7 on 2025-03-25 23:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=255)),
                ('theory', models.PositiveSmallIntegerField()),
                ('practical', models.PositiveSmallIntegerField()),
                ('capacity', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Both')], default='B', max_length=1)),
                ('professor_name', models.CharField(max_length=255)),
                ('class_location', models.CharField(blank=True, max_length=255, null=True)),
                ('prerequisites', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
    ]
