# Generated by Django 5.1.7 on 2025-03-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_create_plan_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.CharField(max_length=31),
        ),
    ]
