# Generated by Django 5.1.7 on 2025-03-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_exam_date_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='practical',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='theory',
            field=models.CharField(max_length=3),
        ),
    ]
