# Generated by Django 5.1.7 on 2025-03-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_model_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='is_problem_solving',
            field=models.BooleanField(default=False),
        ),
    ]
