# Generated by Django 5.1.7 on 2025-04-01 22:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_add_is_problem_solving_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='share_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
