# Generated by Django 5.1.7 on 2025-04-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_add_share_uuid_field_to_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='name',
        ),
    ]
