# Generated by Django 5.1.7 on 2025-05-04 21:13

import django.db.models.deletion
import src.reviews.fields
import src.utill.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_create_faculty_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='professor_profiles/', validators=[src.utill.validators.FileSizeValidator(max_mb=4)])),
                ('office_number', models.CharField(blank=True, max_length=16)),
                ('telegram_account', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('office_location', models.CharField(blank=True, max_length=128)),
                ('schedule_image', models.ImageField(blank=True, null=True, upload_to='professor_schedules/', validators=[src.utill.validators.FileSizeValidator(max_mb=4)])),
                ('student_scores_avg', src.reviews.fields.RatingAvgField(blank=True, decimal_places=2, max_digits=4, max_rating=20, null=True)),
                ('overall_rating', src.reviews.fields.RatingAvgField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('grading_avg', src.reviews.fields.RatingAvgField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('general_knowledge_avg', src.reviews.fields.RatingAvgField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('teaching_engagement_avg', src.reviews.fields.RatingAvgField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('exam_difficulty_avg', src.reviews.fields.RatingAvgField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('homework_difficulty_avg', src.reviews.fields.RatingAvgField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('average_would_take_again', src.reviews.fields.RatingAvgField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professors', to='reviews.faculty')),
            ],
        ),
    ]
