# Generated by Django 5.1.7 on 2025-05-04 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_create_course_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorPageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='reviews.professor')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
    ]
