# Generated by Django 5.1.7 on 2025-05-04 21:39

import django.core.validators
import django.db.models.deletion
import src.reviews.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_create_professorpageview_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=8)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('grading', src.reviews.fields.RatingField()),
                ('exam_difficulty', src.reviews.fields.RatingField()),
                ('general_knowledge', src.reviews.fields.RatingField()),
                ('homework_difficulty', src.reviews.fields.RatingField()),
                ('teaching_engagement', src.reviews.fields.RatingField()),
                ('exam_resources', models.CharField(blank=True, max_length=128)),
                ('attendance_policy', models.CharField(choices=[('mandatory_affects', 'Attendance is important and directly affects grades'), ('optional_positive', 'Attendance is not required but has a positive impact'), ('not_tracked', 'Attendance is not tracked'), ('unknown', "Don't remember")], max_length=32)),
                ('would_take_again', models.BooleanField()),
                ('received_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)])),
                ('review_text', models.CharField(blank=True, max_length=350)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.course')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
