# Generated by Django 5.1.7 on 2025-05-09 17:47
from django.db import migrations
from django.core.management import call_command


def load_faculties(apps, schema_editor):
    """
    Load initial faculty data from fixtures/faculties.json
    """
    call_command('loaddata', 'faculties.json', verbosity=0)


def unload_faculties(apps, schema_editor):
    """
    Remove faculties loaded by this migration (id range 1–15)
    """
    Faculty = apps.get_model('reviews', 'Faculty')
    Faculty.objects.filter(id__range=(1, 15)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_create_professor_revision_model'),
    ]

    operations = [
        migrations.RunPython(load_faculties, reverse_code=unload_faculties),
    ]
