# Generated by Django 5.1.7 on 2025-05-23 19:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_add_three_new_field_to_course_model'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='professorrevision',
            name='unique_pending_revision_per_user_per_prof',
        ),
        migrations.RemoveField(
            model_name='professorrevision',
            name='proposed_courses',
        ),
        migrations.AddField(
            model_name='professorrevision',
            name='proposed_course_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, help_text='List of Course IDs this proposal suggests', size=None),
        ),
    ]
