# Generated by Django 5.1.7 on 2025-05-28 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('close', 'بسته شده'), ('open', 'در حال برسی'), ('answered', 'پاسخ داده شده')], db_index=True, default='open', max_length=8)),
                ('subject', models.CharField(choices=[('financial', 'مالی'), ('technical', 'فنی'), ('suggestion', 'پیشنهادات و انتقادات'), ('advertisement', 'تبلیغات')], db_index=True, max_length=16)),
                ('unit', models.CharField(choices=[('none', 'هیچکدام'), ('courses', 'انتخاب واحد'), ('professors', 'نظرسنجی اساتید'), ('notifications', 'اطلاع\u200cرسانی\u200c')], db_index=True, default='none', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
